import { HomeImageTypes } from "../Types"

export const initialBlogData = {
  title: "",
  author: "",
  link: "",
  image_url: "",
}

export const homeImagesUrls: HomeImageTypes[] = [
  {
    raw_url:
      "https://i.pinimg.com/564x/0b/d7/ef/0bd7ef07df5452c8100173f9c2391a16.jpg",
    post_url: "https://www.pinterest.com/pin/584623595405555143/",
    alt: "Porsche picture",
  },
  {
    raw_url:
      "https://i.pinimg.com/564x/56/81/07/568107616a7dd735e3b862a77b9e6e77.jpg",
    post_url: "https://www.pinterest.com/pin/4714774602782719/",
    alt: "Gym girl",
  },
  {
    raw_url:
      "https://i.pinimg.com/564x/7e/3c/bc/7e3cbc08c129fbef372d90194ec7b8e7.jpg",
    post_url: "https://www.pinterest.com/pin/633248397624618786/",
    alt: "Rich girl with Ferrari",
  },
  {
    raw_url:
      "https://i.pinimg.com/564x/f3/97/b1/f397b100d0a626abed94f0301be44409.jpg",
    post_url: "https://www.pinterest.com/pin/584623595403490046/",
    alt: "2 lamborghinis",
  },

  {
    raw_url:
      "https://i.pinimg.com/564x/f2/03/fa/f203fa2b386633d06467f5d623d5cf49.jpg",
    post_url: "https://www.pinterest.com/pin/4292562137739947/",
    alt: "Healthy food picture",
  },
  {
    raw_url:
      "https://i.pinimg.com/originals/56/b6/ee/56b6ee4732acfbc8078657b5e2a7e37d.jpg",
    post_url: "https://www.pinterest.com/pin/35465915809793452/",
    alt: "Gym girl",
  },
  {
    raw_url:
      "https://i.pinimg.com/564x/73/35/34/73353454e5844ea81ce617517931f1c4.jpg",
    post_url: "https://www.pinterest.com/pin/387450374202487803/",
    alt: "Healthy food picture",
  },
  {
    raw_url:
      "https://i.pinimg.com/564x/39/69/01/396901b74b625c315de597b780438fbf.jpg",
    post_url: "https://www.pinterest.com/pin/64880050875208189/",
    alt: "Healthy food picture",
  },
  {
    raw_url:
      "https://i.pinimg.com/564x/76/52/94/765294d646c1f4af96174490cd47e68f.jpg",
    post_url: "https://www.pinterest.com/pin/1008595279034440674/",
    alt: "Gym girl",
  },
  {
    raw_url:
      "https://i.pinimg.com/564x/18/ac/b7/18acb7372f12afab2a737fa7264d8de6.jpg",
    post_url: "https://www.pinterest.com/pin/584623595403121186/",
    alt: "Gym guy",
  },
  {
    raw_url:
      "https://i.pinimg.com/564x/ac/a0/f0/aca0f00eae889fff1d03d8059db4fb20.jpg",
    post_url: "https://www.pinterest.com/pin/584623595403193129/",
    alt: "Ferrari",
  },
  {
    raw_url:
      "https://i.pinimg.com/564x/35/59/90/3559903b96b32bb2bb4a6829ca657629.jpg",
    post_url: "https://www.pinterest.com/pin/524106475400811789/",
    alt: "Gym guy",
  },
]

export const errorMsgEnding =
  "if error persists contact at lazarevkristijan@gmail.com"

export const defaultPfpURL = "https://i.postimg.cc/G3YzpRnB/ritualelogo.png"

export const allCountries = [
  "Andorra",
  "United Arab Emirates",
  "Afghanistan",
  "Anguilla",
  "Armenia",
  "Angola",
  "Argentina",
  "Austria",
  "Australia",
  "Aruba",
  "Azerbaijan",
  "Bosnia and Herzegovina",
  "Bangladesh",
  "Belgium",
  "Bulgaria",
  "Benin",
  "Bolivia",
  "Brazil",
  "Belarus",
  "Canada",
  "Central African Republic",
  "Switzerland",
  "Chile",
  "Cameroon",
  "China",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Germany",
  "Denmark",
  "Algeria",
  "Ecuador",
  "Estonia",
  "Egypt",
  "Spain",
  "Ethiopia",
  "Finland",
  "France",
  "United Kingdom",
  "Grenada",
  "Georgia",
  "Ghana",
  "Gibraltar",
  "Greenland",
  "Gambia",
  "Guinea",
  "Greece",
  "Guatemala",
  "Hong Kong",
  "Croatia",
  "Haiti",
  "Hungary",
  "Indonesia",
  "Ireland",
  "Israel",
  "India",
  "Iraq",
  "Iran",
  "Iceland",
  "Italy",
  "Jamaica",
  "Jordan",
  "Japan",
  "Kenya",
  "Kyrgyzstan",
  "Cambodia",
  "Kiribati",
  "North Korea",
  "South Korea",
  "Kuwait",
  "Kazakhstan",
  "Lebanon",
  "Liechtenstein",
  "Sri Lanka",
  "Liberia",
  "Lithuania",
  "Luxembourg",
  "Latvia",
  "Libya",
  "Morocco",
  "Monaco",
  "Moldova",
  "Montenegro",
  "Madagascar",
  "Macedonia",
  "Mali",
  "Myanmar",
  "Mongolia",
  "Macao",
  "Northern Mariana Islands",
  "Martinique",
  "Mauritania",
  "Malta",
  "Mauritius",
  "Mongolia",
  "Mexico",
  "Malaysia",
  "Mozambique",
  "Niger",
  "Nigeria",
  "Nicaragua",
  "Netherlands",
  "Norway",
  "Nepal",
  "New Zealand",
  "Panama",
  "Peru",
  "Philippines",
  "Pakistan",
  "Poland",
  "Puerto Rico",
  "Palestine",
  "Portugal",
  "Paraguay",
  "Qatar",
  "Romania",
  "Serbia",
  "Russia",
  "Saudi Arabia",
  "Seychelles",
  "Sudan",
  "Sweden",
  "Singapore",
  "Slovenia",
  "Slovakia",
  "San Marino",
  "Senegal",
  "Somalia",
  "El Salvador",
  "Syria",
  "Chad",
  "Thailand",
  "Tajikistan",
  "Turkmenistan",
  "Tunisia",
  "Turkey",
  "Taiwan",
  "Ukraine",
  "Uganda",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Kosovo",
  "South Africa",
  "Zambia",
  "Zimbabwe",
]

export const countryShorthands = {
  Andorra: "ad",
  "United Arab Emirates": "ae",
  Afghanistan: "af",
  Anguilla: "ai",
  Armenia: "am",
  Angola: "ao",
  Argentina: "ar",
  Austria: "at",
  Australia: "au",
  Aruba: "aw",
  Azerbaijan: "az",
  "Bosnia and Herzegovina": "ba",
  Bangladesh: "bd",
  Belgium: "be",
  Bulgaria: "bg",
  Benin: "bj",
  Bolivia: "bo",
  Brazil: "br",
  Belarus: "by",
  Canada: "ca",
  "Central African Republic": "cf",
  Switzerland: "ch",
  Chile: "cl",
  Cameroon: "cm",
  China: "cn",
  Colombia: "co",
  "Costa Rica": "cr",
  Cuba: "cu",
  Cyprus: "cy",
  "Czech Republic": "cz",
  Germany: "de",
  Denmark: "dk",
  Algeria: "dz",
  Ecuador: "ec",
  Estonia: "ee",
  Egypt: "eg",
  Spain: "es",
  Ethiopia: "et",
  Finland: "fi",
  France: "fr",
  "United Kingdom": "gb",
  Grenada: "gd",
  Georgia: "ge",
  Ghana: "gh",
  Gibraltar: "gi",
  Greenland: "gl",
  Gambia: "gm",
  Guinea: "gn",
  Greece: "gr",
  Guatemala: "gt",
  "Hong Kong": "hk",
  Croatia: "hr",
  Haiti: "ht",
  Hungary: "hu",
  Indonesia: "id",
  Ireland: "ie",
  Israel: "il",
  India: "in",
  Iraq: "iq",
  Iran: "ir",
  Iceland: "is",
  Italy: "it",
  Jamaica: "jm",
  Jordan: "jo",
  Japan: "jp",
  Kenya: "ke",
  Kyrgyzstan: "kg",
  Cambodia: "kh",
  Kiribati: "ki",
  "North Korea": "kp",
  "South Korea": "kr",
  Kuwait: "kw",
  Kazakhstan: "kz",
  Lebanon: "lb",
  Liechtenstein: "li",
  "Sri Lanka": "lk",
  Liberia: "lr",
  Lithuania: "lt",
  Luxembourg: "lu",
  Latvia: "lv",
  Libya: "ly",
  Morocco: "ma",
  Monaco: "mc",
  Moldova: "md",
  Montenegro: "me",
  Madagascar: "mg",
  Macedonia: "mk",
  Mali: "ml",
  Myanmar: "mm",
  Mongolia: "mn",
  Macao: "mo",
  "Northern Mariana Islands": "mp",
  Martinique: "mq",
  Mauritania: "mr",
  Malta: "mt",
  Mauritius: "mu",
  Mexico: "mx",
  Malaysia: "my",
  Mozambique: "mz",
  Niger: "ne",
  Nigeria: "ng",
  Nicaragua: "ni",
  Netherlands: "nl",
  Norway: "no",
  Nepal: "np",
  "New Zealand": "nz",
  Panama: "pa",
  Peru: "pe",
  Philippines: "ph",
  Pakistan: "pk",
  Poland: "pl",
  "Puerto Rico": "pr",
  Palestine: "ps",
  Portugal: "pt",
  Paraguay: "py",
  Qatar: "qa",
  Romania: "ro",
  Serbia: "rs",
  Russia: "ru",
  "Saudi Arabia": "sa",
  Seychelles: "sc",
  Sudan: "sd",
  Sweden: "se",
  Singapore: "sg",
  Slovenia: "si",
  Slovakia: "sk",
  "San Marino": "sm",
  Senegal: "sn",
  Somalia: "so",
  "El Salvador": "sv",
  Syria: "sy",
  Chad: "td",
  Thailand: "th",
  Tajikistan: "tj",
  Turkmenistan: "tm",
  Tunisia: "tn",
  Turkey: "tr",
  Taiwan: "tw",
  Ukraine: "ua",
  Uganda: "ug",
  "United States": "us",
  Uruguay: "uy",
  Uzbekistan: "uz",
  "Vatican City": "va",
  Venezuela: "ve",
  Vietnam: "vn",
  Kosovo: "xk",
  "South Africa": "za",
  Zambia: "zm",
  Zimbabwe: "zw",
}
