export const initialBlogData = {
  title: "",
  author: "",
  link: "",
  image_url: "",
}

export const defaultPfpURL = "https://i.postimg.cc/G3YzpRnB/ritualelogo.png"

export const languages = [
  {
    fullName: "English",
    shortHand: "en",
  },
  {
    fullName: "Spanish",
    shortHand: "es",
  },
  {
    fullName: "Italian",
    shortHand: "it",
  },
  {
    fullName: "German",
    shortHand: "de",
  },
  {
    fullName: "French",
    shortHand: "fr",
  },
]

export const allCountries = [
  "Andorra",
  "United Arab Emirates",
  "Afghanistan",
  "Anguilla",
  "Armenia",
  "Angola",
  "Argentina",
  "Austria",
  "Australia",
  "Aruba",
  "Azerbaijan",
  "Bosnia and Herzegovina",
  "Bangladesh",
  "Belgium",
  "Bulgaria",
  "Benin",
  "Bolivia",
  "Brazil",
  "Belarus",
  "Canada",
  "Central African Republic",
  "Switzerland",
  "Chile",
  "Cameroon",
  "China",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Germany",
  "Denmark",
  "Algeria",
  "Ecuador",
  "Estonia",
  "Egypt",
  "Spain",
  "Ethiopia",
  "Finland",
  "France",
  "United Kingdom",
  "Grenada",
  "Georgia",
  "Ghana",
  "Gibraltar",
  "Greenland",
  "Gambia",
  "Guinea",
  "Greece",
  "Guatemala",
  "Hong Kong",
  "Croatia",
  "Haiti",
  "Hungary",
  "Indonesia",
  "Ireland",
  "Israel",
  "India",
  "Iraq",
  "Iran",
  "Iceland",
  "Italy",
  "Jamaica",
  "Jordan",
  "Japan",
  "Kenya",
  "Kyrgyzstan",
  "Cambodia",
  "Kiribati",
  "North Korea",
  "South Korea",
  "Kuwait",
  "Kazakhstan",
  "Lebanon",
  "Liechtenstein",
  "Sri Lanka",
  "Liberia",
  "Lithuania",
  "Luxembourg",
  "Latvia",
  "Libya",
  "Morocco",
  "Monaco",
  "Moldova",
  "Montenegro",
  "Madagascar",
  "Macedonia",
  "Mali",
  "Myanmar",
  "Mongolia",
  "Macao",
  "Northern Mariana Islands",
  "Martinique",
  "Mauritania",
  "Malta",
  "Mauritius",
  "Mongolia",
  "Mexico",
  "Malaysia",
  "Mozambique",
  "Niger",
  "Nigeria",
  "Nicaragua",
  "Netherlands",
  "Norway",
  "Nepal",
  "New Zealand",
  "Panama",
  "Peru",
  "Philippines",
  "Pakistan",
  "Poland",
  "Puerto Rico",
  "Palestine",
  "Portugal",
  "Paraguay",
  "Qatar",
  "Romania",
  "Serbia",
  "Russia",
  "Saudi Arabia",
  "Seychelles",
  "Sudan",
  "Sweden",
  "Singapore",
  "Slovenia",
  "Slovakia",
  "San Marino",
  "Senegal",
  "Somalia",
  "El Salvador",
  "Syria",
  "Chad",
  "Thailand",
  "Tajikistan",
  "Turkmenistan",
  "Tunisia",
  "Turkey",
  "Taiwan",
  "Ukraine",
  "Uganda",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Kosovo",
  "South Africa",
  "Zambia",
  "Zimbabwe",
]

export const countryShorthands = {
  Andorra: "ad",
  "United Arab Emirates": "ae",
  Afghanistan: "af",
  Anguilla: "ai",
  Armenia: "am",
  Angola: "ao",
  Argentina: "ar",
  Austria: "at",
  Australia: "au",
  Aruba: "aw",
  Azerbaijan: "az",
  "Bosnia and Herzegovina": "ba",
  Bangladesh: "bd",
  Belgium: "be",
  Bulgaria: "bg",
  Benin: "bj",
  Bolivia: "bo",
  Brazil: "br",
  Belarus: "by",
  Canada: "ca",
  "Central African Republic": "cf",
  Switzerland: "ch",
  Chile: "cl",
  Cameroon: "cm",
  China: "cn",
  Colombia: "co",
  "Costa Rica": "cr",
  Cuba: "cu",
  Cyprus: "cy",
  "Czech Republic": "cz",
  Germany: "de",
  Denmark: "dk",
  Algeria: "dz",
  Ecuador: "ec",
  Estonia: "ee",
  Egypt: "eg",
  Spain: "es",
  Ethiopia: "et",
  Finland: "fi",
  France: "fr",
  "United Kingdom": "gb",
  Grenada: "gd",
  Georgia: "ge",
  Ghana: "gh",
  Gibraltar: "gi",
  Greenland: "gl",
  Gambia: "gm",
  Guinea: "gn",
  Greece: "gr",
  Guatemala: "gt",
  "Hong Kong": "hk",
  Croatia: "hr",
  Haiti: "ht",
  Hungary: "hu",
  Indonesia: "id",
  Ireland: "ie",
  Israel: "il",
  India: "in",
  Iraq: "iq",
  Iran: "ir",
  Iceland: "is",
  Italy: "it",
  Jamaica: "jm",
  Jordan: "jo",
  Japan: "jp",
  Kenya: "ke",
  Kyrgyzstan: "kg",
  Cambodia: "kh",
  Kiribati: "ki",
  "North Korea": "kp",
  "South Korea": "kr",
  Kuwait: "kw",
  Kazakhstan: "kz",
  Lebanon: "lb",
  Liechtenstein: "li",
  "Sri Lanka": "lk",
  Liberia: "lr",
  Lithuania: "lt",
  Luxembourg: "lu",
  Latvia: "lv",
  Libya: "ly",
  Morocco: "ma",
  Monaco: "mc",
  Moldova: "md",
  Montenegro: "me",
  Madagascar: "mg",
  Macedonia: "mk",
  Mali: "ml",
  Myanmar: "mm",
  Mongolia: "mn",
  Macao: "mo",
  "Northern Mariana Islands": "mp",
  Martinique: "mq",
  Mauritania: "mr",
  Malta: "mt",
  Mauritius: "mu",
  Mexico: "mx",
  Malaysia: "my",
  Mozambique: "mz",
  Niger: "ne",
  Nigeria: "ng",
  Nicaragua: "ni",
  Netherlands: "nl",
  Norway: "no",
  Nepal: "np",
  "New Zealand": "nz",
  Panama: "pa",
  Peru: "pe",
  Philippines: "ph",
  Pakistan: "pk",
  Poland: "pl",
  "Puerto Rico": "pr",
  Palestine: "ps",
  Portugal: "pt",
  Paraguay: "py",
  Qatar: "qa",
  Romania: "ro",
  Serbia: "rs",
  Russia: "ru",
  "Saudi Arabia": "sa",
  Seychelles: "sc",
  Sudan: "sd",
  Sweden: "se",
  Singapore: "sg",
  Slovenia: "si",
  Slovakia: "sk",
  "San Marino": "sm",
  Senegal: "sn",
  Somalia: "so",
  "El Salvador": "sv",
  Syria: "sy",
  Chad: "td",
  Thailand: "th",
  Tajikistan: "tj",
  Turkmenistan: "tm",
  Tunisia: "tn",
  Turkey: "tr",
  Taiwan: "tw",
  Ukraine: "ua",
  Uganda: "ug",
  "United States": "us",
  Uruguay: "uy",
  Uzbekistan: "uz",
  "Vatican City": "va",
  Venezuela: "ve",
  Vietnam: "vn",
  Kosovo: "xk",
  "South Africa": "za",
  Zambia: "zm",
  Zimbabwe: "zw",
}
